### ISSUE TITLE
誤字脱字および改善できそうな表現の報告

### ISSUE THREAD

**Issue by j-yama** [acroquest/gijyutsu-shoten#1]
書籍読ませていただきました。大変勉強になりました！

さて、誤字脱字表現などを幾つか見つけましたので報告します。
フィードバックとして受け取っていただけますと幸いです。

以降の表では差分のある個所を太字にしています。

## 修正が必要と思われる表現（誤字脱字など）

- 主に誤字脱字と思われる表現です
- また、一部、図と文章のアンマッチや、実行コマンドが見切れていて読み取れないものを含みます

| ページ | 場所  | 表現 | 修正案 | 備考 |
| - | - |-|-|-|
|P.8|表1.2|BASENAMEがない|-|-|
|P.12|表1.3|カテゴーのコントロールパネル|カテゴ**リ**ーのコントロールパネル|-|
|P.12|表1.3|Tag Clo**w**d|Tag Clo**u**d|-|
|P.12|表1.3|Discover**y**|Discover|-|
|P.15|1行目|Tag Clo**w**d|Tag Clo**u**d|-|
|P.15|11行目|数字**は**を表示から省き|数字を表示から省き|-|
|P.20|図1.11|本文中で「Logstashも表示されており」と記載があるが、図ではLogstashは表示されていない|図を差し替えるか本文を修正する|-|
|P.32|3行目|Uni**d**ic|Uni**D**ic|正式な表記|
|P.33|6行目|sudahi.json|suda**c**hi.json|-|
|P.33|6行目|sudahiの辞書ファイル|**S**uda**c**hiの辞書ファイル|-|
|P.33|8行目|"search"3つ|"search"**の**3つ|-|
|P.38|1行目|Uni**d**ic|Uni**D**ic|正式な表記|
|P.38|1行目|**ne**logd|**NEo**logd|-|
|P.40|コード部分3つ目|バイナリ辞書にコンパイルするコマンドが見切れている|-|-|
|P.60|12行目|シャードというもがあります|シャードというも**の**があります|-|
|P.70|4行目|データを蓄積できる**る**こと|データを蓄積できること|-|

## 個人の好みによる表現

- 主に日本語として、こうした方が良いのではないか？という提案です
  - ほか、表記ゆれなど
- この辺りは好みな気もするので、必ずしも修正する必要はないと思います

| ページ | 場所  | 表現 | 修正案 | 備考 |
| - | - |-|-|-|
|P.8|1行目|**敷きい**られている|**仕切**られている or **区切**られている|元々の表記は一般的な表現ではなさそうです|
|P.12|表1.3|PieChart|Pie Chart|他の周りの箇所の表記に合わせてスペースを入れた方が良いと思います|
|P.15|5行目|タイトルの単語の傾向を調べるためには、kuromojiで分割した単語に基づいた解析が必要です。**title付**を設定する場合、タイトル全体で一つの単語として扱われ**ます**。|タイトルの単語の傾向を調べるためには、kuromojiで分割した単語に基づいた解析が必要**なため**です。**「.keyword」ありのtitle**を設定する場合、タイトル全体で一つの単語として扱われ**るため、今回は適しません**。|恐らく執筆内容の意図はこのように読み取りましたが、いかがでしょうか。その場合、現在の書き方だと読者に伝わらない恐れがあります。|
|P.19|1.4.5全般|他のVisualizeの説明では作成画面へたどり着く方法が書いてあるが、メトリクスは書いていない|-|あると親切だと思います|
|P.19|8行目|グループ別**に**表示も可能です|グループ別**の**表示も可能です or グループ別に表示**すること**も可能です|-|
|P.19|9行目|カテゴリ別**の**記事数**の設定が**できます|カテゴリ別**に**記事数**を表示**できます|「の」の連続|
|P.19|表1.9|**i**ndex Pattern|**I**ndex Pattern|ここだけ小文字始まりなのは違和感を覚えました|
|P.21|3行目|逆にテーブルのように詳細を確認する機会は少ないので、|逆にテーブルのように詳細を**表示するもの**を確認する機会は少ないので、|-|
|P.24|1行目|ダッシュボードとDashboardが混在している|-|用語統一の観点|
|P.45|1行目|また、CSV形式もサポートされて**おり、**リクエストパラメータとしてformat=csvと指定します。|また、CSV形式もサポートされて**います。**リクエストパラメータとしてformat=csvと指定します。|無理に言葉を繋げなければ自然になる気がします|
|P.54|10行目|**Elasticsearch** SQLをElssticsearchクエリへ**の**変換できます|**SQLクエリ**をElssticsearchクエリへ変換できます|ここではElasticsearch SQLと呼ばない方が意図が伝わりやすいかと思います|
|P.60|15行目|高速**で**検索できます|高速**に**検索できます|-|
|P.61|15行目|Elasticsearch**に**は、データの冗長化をソフトウェアとして実現しています。|Elasticsearch**で**は、データの冗長化をソフトウェアとして実現しています。|-|
|P.62|4行目|Data node2|Data node 2|ほか、全般的にShard1となっていたり、Shard 1となっていたり空白の有無がまちまちな気がします。優先度は低いですし、著者横断の書籍全体で統一する必要はないと思いますが、空白が空いていた方が個人的には美しいかと思いました。（図での表記は空白を空けることで統一されていらっしゃいますね。）|
|P.77|10行目|１ノードあたり**の**600～750|１ノードあたり600～750|表現として「の」は不要な気がしますがいかがでしょうか。|

**Comment by snuffkin** [comment]
誤字脱字、すみませんでした。
また、読み込んでくださってのご指摘ありがとうございます。大変感謝しております。
内容を確認し、正誤表を公開する等いたします。

本当にありがとうございます。

**Comment by snuffkin** [comment]
@j-yama 
ありがとうございました。
正誤表として、反映いたしました。
https://github.com/acroquest/gijyutsu-shoten#%E6%AD%A3%E8%AA%A4%E8%A1%A8

「個人の好みによる表現」の一部はそのままとしました。
